export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const SIGNOUT = 'SIGNOUT'

export const USER_LOAD = 'USER_LOAD'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_CLEAR = 'USER_CLEAR'

export const GUIDANCE_LOAD = 'GUIDANCE_LOAD'
export const GUIDANCE_UPDATE = 'GUIDANCE_UPDATE'

export const ASSISTANCE_LOAD = 'ASSISTANCE_LOAD'
export const ASSISTANCE_UPDATE = 'ASSISTANCE_UPDATE'
export const ASSISTANCE_DELETE = 'ASSISTANCE_DELETE'

export const ASSISTANCE_INFO_LOAD = 'ASSISTANCE_INFO_LOAD'
export const ASSISTANCE_INFO_UPDATE = 'ASSISTANCE_INFO_UPDATE'
